# 单机模式
server.servlet.contextPath=/nacos
server.port=8848

# 使用 MySQL 数据源
spring.datasource.platform=mysql

# 连接计数
db.num=1
db.url.0=jdbc:mysql://minichat-mysql:3306/minichat_nacos?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
db.user.0=root
db.password.0=your_secure_password

# 关闭默认的内嵌 Derby
nacos.cmdb.dumpTaskInterval=3600
nacos.cmdb.eventTaskInterval=10
nacos.cmdb.labelTaskInterval=300
nacos.cmdb.loadDataAtStart=false

# security
nacos.core.auth.enabled=false
nacos.core.auth.system.type=nacos
