server:
  port: 8080

spring:
  codec:
    max-in-memory-size: 50MB
  application:
    name: minichat-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        ip: 127.0.0.1
    gateway:
      routes:
        - id: user-service
          uri: lb://minichat-user
          predicates:
            - Path=/auth/**,/user/**,/friend/**,/group/**,/file/**,/internal/**
        - id: message-service
          uri: lb://minichat-message
          predicates:
            - Path=/message/**,/conversation/**,/oss/**
        - id: ws-message-service
          uri: lb://minichat-message
          predicates:
            - Path=/ws/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true

jwt:
  secret: MiniChatSecretKey2026MustBeAtLeast256BitsLongForHMACSHA256!

logging:
  level:
    com.minichat: debug
    org.springframework.cloud.gateway: debug
